### ISSUE TITLE
I saw your post to the PyBasic repository :)

### ISSUE THREAD

**Issue by RetiredWizard** [brickbots/PicoBasic#1]
Hi brickbots :)

We must be tuned into the same wave lengths, I've made most of the same mods to richpl's awesome interpreter, however I'm really not well versed in github so I didn't attempt the pull requests. I'm glad you did. You might be interested in the RP2040 DOS shell I cobbled together https://github.com/RetiredWizard/PyDOS or the forked copy of PyBasic I have at https://github.com/RetiredWizard/PyBasic/releases/tag/v1.83c.

One significant mod I've made to the richpl version is that I don't load the basic program into ram but create an index to line numbers and then execute the code in place on the flash. This has allowed me to run surprisingly large basic programs.

**Comment by brickbots** [comment]
Hi @RetiredWizard!  

Indeed it does seems like fortuitous timing!  I saw your PyDos project linked from your issue in the PyBasic repo and am very impressed.  The PyDos effort is very ambitious and I'd be curious to know if you have additional features on the roadmap?

Your video demo was really informative and covered so many awesome things and I have a bunch of questions/thoughts that are sort of a hodgepodge, so forgive the unstructured nature here.  Also, feel free to email me: rich at brickbots.com if you'd like to further discuss or collaborate on any of this :-)

First, a quick rundown of what I'm up to, since I've not put together a good readme here yet.  This repo is for my handheld basic computer project based on the RP2040.  It's currently aimed at two different hardware platforms:

The PICOmputer:
https://github.com/bobricius/PICOmputer

And the Keyfeather:
https://www.adafruit.com/product/4818

Here are some photos of it in action on a PICOmputer:
https://imgur.com/a/AfzUZYI
Forgive the terrible image quality and cat hair....

=============

Looking at your change log from PyBasic it looks like we've been pursuing the same basic goals, which is awesome.  
* Improve compatibility with 'vintage basics'
* Keep an eye on memory use!
* Add some use-case specific enhancements/niceties

This repo has my working copy of PyBasic with a heap of changes that I didn't really cleanly track.  My fork of the actual PyBasic repo is where I'm branching and reimplementing these features in reasonable size chunks.  This repo also has all the hardware abstraction basics for keyboard, screen and sound (buzzer based on GP0).  

###Vintage basic:
I've got most of the key syntax changes here that you have implemented along with some of the new keywords/functions.  You've definitely nailed some I've not put in place yet, and I have a couple you might end up wanting (left$ / right$).  Looks like we've both fixed up the array and string indexing to make it less pythonic and more basic :-)

###Compound Statements:
Looks like we both have an almost complete multi-statement one one line implementation, but from the video it looks like we share the same defect around loops in compound lines.  That's a tricky one, and I'm thinking of ditching my implementation for a different approach where these compound statements are decomposed in loading into individual lines.  If I go this route, I'll be making a 'statement' class to replace all this token-list / line number list stuff.  The line numbers will just become visual labels so this will also allow renumbering programs / inserting statements where there has been insufficient line number gapping.   It could potentially take more memory.....

###Memory Management:
You've pushed a lot further here than I have and I'm keen to really dig into your code.  I implemented a FREE command in the interpreter to help watch how memory is consumed.   My primary strategy so far has been to freeze as much of the python code for PyBasic and the HAL into the firmware itself.  This runs all the python code in place and allows almost 200k for PyBasic.  I'm not sure if you are doing this with PyDOS, but it's not that disruptive and can be a big savings.  It does require getting the firmware building toolchain up and running, but there is a nice guide for CircuitPython.

Your method of running the basic code in place is pretty cool.  Does it affect speed much?  I was going to work to minimize the program/statement structure memory overhead overall but still try to load the tokenized program fully into memory.  I'll have to rethink that!

One of the things that's been exceptionally useful the tiny screens I'm targeting is paginated program listings.  I've implemented this and was looking to incorporate starting on a specific page (LIST 100 would make sure line 100 was at the middle of the screen with the page of the program listing around it).  With a slightly more sophisticated terminal abstraction (mine uses VT100 codes, so your vga adapter might already work).  

###Hardware / Terminal:
How do you feel about abstracting the print/input stuff to a 'terminal' class passed into the interpreter?
Not sure how this might work with PyDOS, but there could be a simple class that just does print/input from stdio so it would function just like it does now.  A curses based one so that screen positioning could work, and then hardware specific ones for button keyboards/various displays.

Along with a sound implementation, I've also implemented CLEAR, HOME and CURSOR commands to allow slightly more complex text games and paginated program listing / edit in place (a-la C64... list a program and use the arrow keys to move to a line, then edit it and press enter to save it back to the program list).  To support the game use case, I've also implemented a GETCHR command to wait for just a single character from the keyboard and POLLCHR to see if any key is pressed without waiting for one.

I'm also hoping to do a simple graphics mode, but I'm not certain about that with the memory constraints.

###Module Packaging:
PyBasic feels to me like it should be a module, with all the various .py files in a single namespace i.e.
```
from pybasic import interpreter
interpreter.main()
```
This enables this module to be a sub-repo in a larger repo and could allow the same base PyBasic repo to be used in both of our projects if we could merge the codebases.

###Collaboration:
First off.. awesome work here, I'm really impressed.  At the very least, may I copy some of your code here to improve my version of vintage basic compatibility?
Or
Should we collaborate and I can fork your pybasic repo and start some pull requests to implement more of the dialect and the module/terminal abstraction stuff?

I'm keen to see if the original author will be interested in vintage basic compatibility as it's a pretty big change.  Even if he does accept some of the overall changes, I feel like there are some areas where my/your versions will probably have to ditch cPython compatibility to really get where we are hoping to go.... so I think I'll always be using some fork of the original, it just might be cool if it's not tooooo far off.
